import { ExpectedEvidence } from "./EvidenceCollectionReviewTable";

export const expectedEvidences: ExpectedEvidence[] = [
  {
    id: 1,
    planCode: "KH-KTPM-2024",
    trainingProgram: "Kỹ thuật phần mềm",
    accreditaionCode: "2021-2026",
    groupCode: "NCT_TC5-7",
    responsibleMember: "ThS. Hoàng Thị E",
    standardCode: "TC_05",
    criterionCode: "TC_05.02",
    expectedCode: "H5.05.02.01",
    expectedName: "Quyết định ban hành Quy chế đào tạo trình độ ĐH",
    actualCode: "H5.05.02.01",
    actualName: "Quyết định ban hành Quy chế đào tạo ĐH (2025)",
    issueNumber: "Số 456/QĐ-ĐT",
    issueDate: "Ngày 20/01/2025",
    issuedBy: "Trường Đại học Đồng Nai",
    fileUrl: "test",
    link: "http://drive.google.com/link_quyche_2025_v2",
    note: "",
    approvalStatus: 1,
    comment: "",
  },
  {
    id: 2,
    planCode: "KH-KTPM-2024",
    trainingProgram: "Kỹ thuật phần mềm",
    accreditaionCode: "2021-2026",
    groupCode: "NCT_TC5-7",
    responsibleMember: "ThS. Hoàng Thị E",
    standardCode: "TC_05",
    criterionCode: "TC_05.02",
    expectedCode: "H5.05.02.02",
    expectedName: "Báo cáo khảo sát SV về Quy chế đào tạo",
    actualCode: "H5.05.02.02",
    actualName: "Báo cáo tổng kết công tác khảo sát ý kiến SV (2024)",
    issueNumber: "",
    issueDate: "Ngày 10/12/2024",
    issuedBy: "Phòng Đảm bảo Chất lượng",
    fileUrl: "test",
    link: "http://drive.google.com/link_baocao_ks",
    note: "",
    approvalStatus: 2,
    comment: "",
  },
  {
    id: 3,
    planCode: "KH-KTPM-2024",
    trainingProgram: "Kỹ thuật phần mềm",
    accreditaionCode: "2021-2026",
    groupCode: "NCT_TC1-3",
    responsibleMember: "TS. Trần Văn C",
    standardCode: "TC_01",
    criterionCode: "TC_01.01",
    expectedCode: "H1.01.01.01",
    expectedName: "Quyết định về mục tiêu và chuẩn đầu ra cao CTĐT",
    actualCode: "H1.01.01.01",
    actualName: "Quyết định về mục tiêu và chuẩn đầu ra KTPM (2024)",
    issueNumber: "Số 123/QĐ-KHMT",
    issueDate: "Ngày 15/05/2024",
    issuedBy: "Khoa Khoa học Máy tính",
    fileUrl: "test",
    link: "http://drive.google.com/link_cdr_ktpm",
    note: "",
    approvalStatus: 3,
    comment: "",
  },
  {
    id: 4,
    planCode: "KH-KTPM-2024",
    trainingProgram: "Kỹ thuật phần mềm",
    accreditaionCode: "2021-2026",
    groupCode: "NCT_TC3-4",
    responsibleMember: "CN. Bùi Thị L",
    standardCode: "TC_03",
    criterionCode: "TC_03.02",
    expectedCode: "H3.03.02.05",
    expectedName: "Danh sách cán bộ viên chức cơ hữu",
    actualCode: "H3.03.02.05",
    actualName: "Danh sách CBGV Khoa CNTT (HK1_24-25)",
    issueNumber: "",
    issueDate: "Ngày 01/09/2024",
    issuedBy: "Phòng Tổ chức Cán bộ",
    fileUrl: "test",
    link: "http://drive.google.com/link_ds_gvcn",
    note: "",
    approvalStatus: 2,
    comment: "",
  },
  {
    id: 5,
    planCode: "KH-KTPM-2024",
    trainingProgram: "Kỹ thuật phần mềm",
    accreditaionCode: "2021-2026",
    groupCode: "NCT_TC2-4",
    responsibleMember: "ThS. Nguyễn Thị K",
    standardCode: "TC_02",
    criterionCode: "TC_02.01",
    expectedCode: "H2.02.01.03",
    expectedName: "Danh mục đề cương chi tiết học phần",
    actualCode: "",
    actualName: "",
    issueNumber: "",
    issueDate: "",
    issuedBy: "",
    fileUrl: "",
    link: "",
    note: "",
    approvalStatus: -1,
    comment: "",
  },
];