import {
  IRecordResultsCollectRealWorldEvidenceInfoViewModel,
  ICollectEvidenceInfoViewModel,
  ITabEvidenceVersionInfoViewModel,
  ITabPlaceToUseInfoViewModel,
} from "./interfaces";
export const mockDataRecordResultsCollectRealWorldEvidence: IRecordResultsCollectRealWorldEvidenceInfoViewModel[] =
  [
    {
      maKeHoachTdg: "KH-KTPM-2024",
      maNhomCt: "NCT_TC5-7",
      thanhVienPhuTrach: "ThS. Hoàng Thị E",
      maTieuChuan: "TC_05",
      maTieuChi: "TC_05.02",
      maMcDuKien: "H5.05.02.01",
      tenMcDuKien: "Quyết định ban hành Quy chế đào tạo trình độ ĐH",
      maMcThucTe: "H5.05.02.01",
      tenMc: "Quyết định ban hành Quy chế đào tạo ĐH (2025)",
      soNgayBanHanh: "Số 456/QĐ-ĐT Ngày 2025-01-20",
      donViBanHanh: "Trường Đại học Đồng Nai",
      fileDinhKem: "file.pdf",
      linkLienKet: "https://drive.google.com/link_quyche_2025_v2",
      ghiChu: undefined,
      trangThaiKiemDuyetMc: "Chưa kiểm duyệt",
    },
    {
      maKeHoachTdg: "KH-KTPM-2024",
      maNhomCt: "NCT_TC5-7",
      thanhVienPhuTrach: "ThS. Hoàng Thị E",
      maTieuChuan: "TC_05",
      maTieuChi: "TC_05.02",
      maMcDuKien: "H5.05.02.02",
      tenMcDuKien: "Báo cáo khảo sát SV và Quy chế đào tạo",
      maMcThucTe: "H5.05.02.02",
      tenMc: "Báo cáo tổng kết công tác khảo sát ý kiến SV (2024)",
      soNgayBanHanh: "Ngày 2024-12-10",
      donViBanHanh: "Phòng Đảm bảo Chất lượng",
      fileDinhKem: "file.pdf",
      linkLienKet: "https://drive.google.com/link_baocao_xk",
      ghiChu: undefined,
      trangThaiKiemDuyetMc: "Đã kiểm duyệt",
    },
    {
      maKeHoachTdg: "KH-KTPM-2024",
      maNhomCt: "NCT_TC1-3",
      thanhVienPhuTrach: "TS. Trần Văn C",
      maTieuChuan: "TC_01",
      maTieuChi: "TC_01.01",
      maMcDuKien: "H1.01.01.01",
      tenMcDuKien: "Quyết định về mục tiêu và chuẩn đầu ra của CTĐT",
      maMcThucTe: "H1.01.01.01",
      tenMc: "Quyết định về mục tiêu và chuẩn đầu ra KTPM (2024)",
      soNgayBanHanh: "Số 123/QĐ-KHMT Ngày 2024-05-15",
      donViBanHanh: "Khoa Khoa học Máy tính",
      fileDinhKem: "file.pdf",
      linkLienKet: "https://drive.google.com/link_cdr_ktpm",
      ghiChu: undefined,
      trangThaiKiemDuyetMc: "Yêu cầu bổ sung/hiệu chỉnh",
    },
    {
      maKeHoachTdg: "KH-KTPM-2024",
      maNhomCt: "NCT_TC3-4",
      thanhVienPhuTrach: "CN. Bùi Thị L",
      maTieuChuan: "TC_03",
      maTieuChi: "TC_02.01",
      maMcDuKien: "H3.03.02.05",
      tenMcDuKien: "Danh sách cán bộ giảng viên cơ hữu",
      maMcThucTe: "H3.03.02.05",
      tenMc: "Danh sách CBGV Khoa CNTT (HK1_24-25)",
      soNgayBanHanh: "Ngày 2024-09-01",
      donViBanHanh: "Phòng Tổ chức Cán bộ",
      fileDinhKem: "file.pdf",
      linkLienKet: "https://drive.google.com/link_ds_giao_vien",
      ghiChu: undefined,
      trangThaiKiemDuyetMc: "Đã kiểm duyệt",
    },
    {
      maKeHoachTdg: "KH-KTPM-2024",
      maNhomCt: "NCT_TC2-4",
      thanhVienPhuTrach: "ThS. Nguyễn Thị K",
      maTieuChuan: "TC_02",
      maTieuChi: "TC_02.01",
      maMcDuKien: "H2.02.01.03",
      tenMcDuKien: "Danh sách cán bộ giảng viên cơ hữu",
      maMcThucTe: undefined,
      tenMc: undefined,
      soNgayBanHanh: undefined,
      donViBanHanh: undefined,
      fileDinhKem: undefined,
      linkLienKet: undefined,
      ghiChu: undefined,
      trangThaiKiemDuyetMc: undefined,
    },
  ];

export const mockDataCollectEvidence: ICollectEvidenceInfoViewModel[] = [
  {
    maMinhChung: "H5.05.02.01",
    tenMinhChung: "Quyết định ban hành Quy chế đào tạo trình độ ĐH của Trường",
    maMcTrucThuocCha: undefined,
    soNgayBanHanh: "Số 456/QĐ-ĐT Ngày 20/01/2025",
    donViBanHanh: "Trường Đại học Đồng Nai",
    hieuLucTuNgay: "2025-02-01",
    hieuLucDenNgay: "2027-01-31",
    trangThaiHieuLuc: "Còn hạn",
    fileDinhKem: "file.pdf",
    linkLienKet: "https://drive.google.com/link_quyche_2025_v2",
    ghiChu:
      "Là văn bản pháp lý nền tảng cho hoạt động đào tạo đại học. Cần phiên bản có hiệu lực.",
  },
  {
    maMinhChung: "H5.05.02.02",
    tenMinhChung:
      "Báo cáo tổng kết công tác khảo sát ý kiến SV và Quy chế đào tạo",
    maMcTrucThuocCha: undefined,
    soNgayBanHanh: "Ngày 10/12/2024",
    donViBanHanh: "Phòng Đảm bảo Chất lượng",
    hieuLucTuNgay: "2024-09-01",
    hieuLucDenNgay: "2024-12-31",
    trangThaiHieuLuc: "Hết hạn",
    fileDinhKem: "file.pdf",
    linkLienKet: "https://drive.google.com/link_baocao_ks",
    ghiChu: "Tổng hợp ý kiến phản hồi của sinh viên về quy chế đào tạo.",
  },
  {
    maMinhChung: "H1.01.01.01",
    tenMinhChung: "Quyết định về mục tiêu và chuẩn đầu ra của CTĐT KTPM",
    maMcTrucThuocCha: undefined,
    soNgayBanHanh: "Số 123/QĐ-KHMT Ngày 15/05/2024",
    donViBanHanh: "Khoa Khoa học Máy tính",
    hieuLucTuNgay: "2024-09-01",
    hieuLucDenNgay: "2028-08-31",
    trangThaiHieuLuc: "Còn hạn",
    fileDinhKem: "file.pdf",
    linkLienKet: "https://drive.google.com/link_cdr_ktpm",
    ghiChu: "Văn bản chính thức quy định chuẩn đầu ra cho CTĐT KTPM.",
  },
  {
    maMinhChung: "H1.01.01.01.01",
    tenMinhChung: "Biên bản họp Hội đồng Khoa học về sửa đổi CĐR",
    maMcTrucThuocCha: "H1.01.01.01",
    soNgayBanHanh: "Ngày 10/01/2025",
    donViBanHanh: "Hội đồng Khoa học Trường",
    hieuLucTuNgay: "2025-01-10",
    hieuLucDenNgay: undefined,
    trangThaiHieuLuc: "Còn hạn",
    fileDinhKem: "file.pdf",
    linkLienKet: "https://drive.google.com/link_bbhop_2025",
    ghiChu: "Biên bản ghi nhận quá trình thảo luận và sửa đổi chuẩn đầu ra.",
  },
];

export const mockDataTabEvidenceVersion: ITabEvidenceVersionInfoViewModel[] =
  [
    {
      idFile: "FILE_ID_0001",
      tenFile: "Quyết định ban hành Quy chế đào tạo ĐH (2025)",
      fileDinhKem: "file.pdf",
      linkLienKet: "https://drive.google.com/link_quyche_2025_v2",
      soNgayBanHanh: "Số 456/QĐ-ĐT Ngày 20/01/2025",
      donViBanHanhCap: "Trường Đại học Đồng Nai",
      hieuLucTuNgay: "2025-02-01",
      hieuLucDenNgay: "2027-01-31",
      ghiChuPhienBan: "Phiên bản mới nhất sau đợt rà soát định kỳ 2025.",
      hienHanh: true,
    },
    {
      idFile: "FILE_ID_0006",
      tenFile: "Quyết định ban hành Quy chế đào tạo ĐH (2023)",
      fileDinhKem: "file.pdf",
      linkLienKet: "https://drive.google.com/link_quyche_2023",
      soNgayBanHanh: "Số 789/QĐ-ĐT Ngày 15/01/2023",
      donViBanHanhCap: "Trường Đại học Đồng Nai",
      hieuLucTuNgay: "2023-02-01",
      hieuLucDenNgay: "2025-01-31",
      ghiChuPhienBan:
        "Phiên bản Quy chế đào tạo áp dụng cho giai đoạn 2023-2025.",
      hienHanh: false,
    },
    {
      idFile: "FILE_ID_0007",
      tenFile: "Biên bản họp Hội đồng Khoa học về sửa đổi Quy chế ĐT (2025)",
      fileDinhKem: "file.pdf",
      linkLienKet: "https://drive.google.com/link_bbhop_2025",
      soNgayBanHanh: "Ngày 2025-01-10",
      donViBanHanhCap: "Hội đồng Khoa học Trường",
      hieuLucTuNgay: "2025-01-10",
      hieuLucDenNgay: undefined,
      ghiChuPhienBan:
        "Là tài liệu nền tảng cho Quyết định ban hành Quy chế đào tạo 2025.",
      hienHanh: false,
    },
  ];

export const mockDataPlaceToUseTab: ITabPlaceToUseInfoViewModel[] = [
  {
    maKeHoachTdg: "KH-KTPM-2024",
    maCtdt: "KTPM",
    khoa: "K2020",
    maTieuChuan: "TC_05",
    maTieuChi: "TC_05.02",
    maMinhChung: "H5.05.02.01",
    idFileHeThong: "FILE_ID_0001",
    tenFileHienThi: "Quyết định ban hành Quy chế đào tạo ĐH (2025)",
    fileDinhKem: "Xem file",
    linkLienKet: "https://drive.google.com/link_quyche_2025",
    soNgayBanHanh: "Số 456/QĐ-ĐT Ngày 20/01/2025",
    donViBanHanhCap: "Trường Đại học Đồng Nai",
    hieuLucTuNgay: "2025-02-01",
    hieuLucDenNgay: "2027-01-31",
  },
  {
    maKeHoachTdg: "KH-KTPM-2024",
    maCtdt: "KTPM",
    khoa: "K2021",
    maTieuChuan: "TC_05",
    maTieuChi: "TC_05.02",
    maMinhChung: "H5.05.02.01",
    idFileHeThong: "FILE_ID_0001",
    tenFileHienThi: "Quyết định ban hành Quy chế đào tạo ĐH (2025)",
    fileDinhKem: "Xem file",
    linkLienKet: "https://drive.google.com/link_quyche_2025",
    soNgayBanHanh: "Số 456/QĐ-ĐT Ngày 20/01/2025",
    donViBanHanhCap: "Trường Đại học Đồng Nai",
    hieuLucTuNgay: "2025-02-01",
    hieuLucDenNgay: "2027-01-31",
  },
  {
    maKeHoachTdg: "KH-KT_2025",
    maCtdt: "KT",
    khoa: "K2019",
    maTieuChuan: "TC_05",
    maTieuChi: "TC_05.02",
    maMinhChung: "H5.05.02.01",
    idFileHeThong: "FILE_ID_0001",
    tenFileHienThi: "Quyết định ban hành Quy chế đào tạo ĐH (2025)",
    fileDinhKem: "Xem file",
    linkLienKet: "https://drive.google.com/link_quyche_2025",
    soNgayBanHanh: "Số 456/QĐ-ĐT Ngày 20/01/2025",
    donViBanHanhCap: "Trường Đại học Đồng Nai",
    hieuLucTuNgay: "2025-02-01",
    hieuLucDenNgay: "2027-01-31",
  },
  {
    maKeHoachTdg: "KH-KTPM-2024",
    maCtdt: "KTPM",
    khoa: "K2020",
    maTieuChuan: "TC_01",
    maTieuChi: "TC_01.01",
    maMinhChung: "H1.01.01.01",
    idFileHeThong: "FILE_ID_0003",
    tenFileHienThi: "Quyết định về mục tiêu và chuẩn đầu ra KTPM (2024)",
    fileDinhKem: "Xem file",
    linkLienKet: "https://drive.google.com/link_cdr_ktpm",
    soNgayBanHanh: "Số 123/QĐ-KHMT Ngày 15/05/2024",
    donViBanHanhCap: "Khoa Khoa học Máy tính",
    hieuLucTuNgay: "2024-09-01",
    hieuLucDenNgay: "2028-08-31",
  },
];

export const selectTrucThuocMinhChung: string[] = [
  "H5.05.02.01",
  "H5.05.02.02",
  "H1.01.01.01",
  "H1.01.01.01.01"
]